apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "genai-rag.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "genai-rag.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "genai-rag.name" . }}
    spec:
      containers:
        - name: rag-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL }}
            - name: MILVUS_HOST
              value: {{ .Values.env.MILVUS_HOST }}
            - name: MILVUS_PORT
              value: "{{ .Values.env.MILVUS_PORT }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
